version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Tokyo

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Tokyo
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
